services:

  mysql:
    image: mysql:8.4

    container_name: sci_mysql

    environment:
      MYSQL_DATABASE: sci_coffee
      MYSQL_USER: sci
      MYSQL_PASSWORD: sci123
      MYSQL_ROOT_PASSWORD: root123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
